export const categories = [
  { id: "video", label: "Video Editing", icon: "🎬", color: "from-red-500/20 to-orange-500/20", border: "border-red-500/20", count: 1240 },
  { id: "photo", label: "Photo Editing", icon: "📷", color: "from-cyan-500/20 to-blue-500/20", border: "border-cyan-500/20", count: 980 },
  { id: "motion", label: "Motion Graphics", icon: "✨", color: "from-indigo-500/20 to-purple-500/20", border: "border-indigo-500/20", count: 654 },
  { id: "audio", label: "Sound Design", icon: "🎵", color: "from-green-500/20 to-emerald-500/20", border: "border-green-500/20", count: 432 },
  { id: "ai", label: "AI Tools", icon: "🤖", color: "from-pink-500/20 to-rose-500/20", border: "border-pink-500/20", count: 876 },
  { id: "templates", label: "Templates", icon: "🗂️", color: "from-yellow-500/20 to-amber-500/20", border: "border-yellow-500/20", count: 2100 },
  { id: "fonts", label: "Fonts", icon: "🔤", color: "from-purple-500/20 to-violet-500/20", border: "border-purple-500/20", count: 340 },
  { id: "color", label: "Color Palettes", icon: "🎨", color: "from-orange-500/20 to-red-500/20", border: "border-orange-500/20", count: 567 },
  { id: "luts", label: "LUTs & Presets", icon: "🎞️", color: "from-teal-500/20 to-cyan-500/20", border: "border-teal-500/20", count: 890 },
  { id: "stock", label: "Stock Media", icon: "🖼️", color: "from-blue-500/20 to-indigo-500/20", border: "border-blue-500/20", count: 3200 },
  { id: "plugins", label: "Plugins", icon: "🔌", color: "from-violet-500/20 to-purple-500/20", border: "border-violet-500/20", count: 478 },
  { id: "tutorials", label: "Tutorials", icon: "📚", color: "from-emerald-500/20 to-green-500/20", border: "border-emerald-500/20", count: 1560 },
];

export type Resource = {
  id: string;
  title: string;
  description: string;
  category: string;
  tags: string[];
  badge?: "trending" | "new" | "official";
  stars: number;
  saves: number;
  downloads: number;
  author: {
    name: string;
    avatar: string;
    verified: boolean;
  };
  thumbnail: string;
  type: "free" | "premium";
  preview?: string;
};

export const resources: Resource[] = [
  {
    id: "1",
    title: "Cinematic LUT Pack Pro",
    description: "20 LUTs cinematográficos profesionales para darle un look Hollywood a tus vídeos. Compatible con Premiere, DaVinci Resolve y FCPX.",
    category: "luts",
    tags: ["video", "luts", "cinematic"],
    badge: "trending",
    stars: 4.9,
    saves: 12400,
    downloads: 45200,
    author: { name: "VisualCraft", avatar: "VC", verified: true },
    thumbnail: "luts",
    type: "free",
  },
  {
    id: "2",
    title: "Motion Blur Transitions Pack",
    description: "50 transiciones con motion blur suave para Premiere Pro y After Effects. Instalación drag & drop, sin plugins adicionales.",
    category: "motion",
    tags: ["motion", "templates", "video"],
    badge: "new",
    stars: 4.8,
    saves: 8900,
    downloads: 31000,
    author: { name: "TransitionKing", avatar: "TK", verified: false },
    thumbnail: "motion",
    type: "free",
  },
  {
    id: "3",
    title: "AI Background Remover API",
    description: "Integración con IA para eliminar fondos automáticamente. Soporta imágenes en batch y vídeos en tiempo real con 99% de precisión.",
    category: "ai",
    tags: ["ai", "photo", "automation"],
    badge: "official",
    stars: 4.7,
    saves: 22100,
    downloads: 89000,
    author: { name: "AIStudio", avatar: "AI", verified: true },
    thumbnail: "ai",
    type: "premium",
  },
  {
    id: "4",
    title: "Lofi Music Pack — 30 tracks",
    description: "30 tracks de música lofi libre de derechos para YouTube, Twitch y podcast. Incluye 320kbps MP3 + WAV sin compresión.",
    category: "audio",
    tags: ["audio", "music", "free"],
    badge: "trending",
    stars: 4.9,
    saves: 31500,
    downloads: 120000,
    author: { name: "SoundForge", avatar: "SF", verified: true },
    thumbnail: "audio",
    type: "free",
  },
  {
    id: "5",
    title: "Minimal Instagram Templates",
    description: "100 templates para Stories e Instagram Feed con estética minimalista. Totalmente editables en Canva y Figma.",
    category: "templates",
    tags: ["templates", "design", "social"],
    badge: "new",
    stars: 4.6,
    saves: 14800,
    downloads: 67000,
    author: { name: "DesignBox", avatar: "DB", verified: false },
    thumbnail: "templates",
    type: "free",
  },
  {
    id: "6",
    title: "Lightroom Preset Collection",
    description: "200 presets para Lightroom con estilo editorial. Incluye filtros para outdoor, portrait, urban y food photography.",
    category: "photo",
    tags: ["photo", "presets", "lightroom"],
    badge: "official",
    stars: 4.8,
    saves: 19200,
    downloads: 78000,
    author: { name: "PhotoPro", avatar: "PP", verified: true },
    thumbnail: "photo",
    type: "premium",
  },
  {
    id: "7",
    title: "Glitch FX Overlay Pack",
    description: "80 overlays de glitch, ruido VHS y distorsión digital para After Effects y Premiere. Perfectos para contenido retro y cyberpunk.",
    category: "motion",
    tags: ["motion", "video", "effects"],
    stars: 4.5,
    saves: 6700,
    downloads: 24000,
    author: { name: "GlitchLab", avatar: "GL", verified: false },
    thumbnail: "motion",
    type: "free",
  },
  {
    id: "8",
    title: "YouTube Thumbnail Templates",
    description: "50 plantillas de thumbnails para YouTube con alta tasa de click (CTR). Totalmente editables en Photoshop y Canva.",
    category: "templates",
    tags: ["templates", "youtube", "design"],
    badge: "trending",
    stars: 4.7,
    saves: 25000,
    downloads: 98000,
    author: { name: "ThumbnailPro", avatar: "TP", verified: true },
    thumbnail: "templates",
    type: "free",
  },
  {
    id: "9",
    title: "Sound FX Mega Pack",
    description: "500+ efectos de sonido categorizados: ambiente, impactos, UI, naturaleza y más. Calidad de estudio: 48kHz/24bit.",
    category: "audio",
    tags: ["audio", "sfx", "free"],
    badge: "new",
    stars: 4.9,
    saves: 42000,
    downloads: 156000,
    author: { name: "AudioVault", avatar: "AV", verified: true },
    thumbnail: "audio",
    type: "free",
  },
  {
    id: "10",
    title: "Display Font Collection",
    description: "60 fuentes display premium para títulos y portadas. Incluye versiones serif, sans-serif y display con distintos pesos.",
    category: "fonts",
    tags: ["fonts", "design", "templates"],
    badge: "new",
    stars: 4.6,
    saves: 9800,
    downloads: 38000,
    author: { name: "TypeLab", avatar: "TL", verified: true },
    thumbnail: "fonts",
    type: "free",
  },
  {
    id: "11",
    title: "TikTok & Reels Template Kit",
    description: "120 templates verticales optimizados para TikTok, Reels e YouTube Shorts. Animaciones fluidas editables en CapCut y Premiere.",
    category: "templates",
    tags: ["templates", "video", "social"],
    badge: "trending",
    stars: 4.8,
    saves: 33000,
    downloads: 142000,
    author: { name: "ShortFormPro", avatar: "SP", verified: true },
    thumbnail: "templates",
    type: "free",
  },
  {
    id: "12",
    title: "Photoshop Actions Bundle",
    description: "150 acciones de Photoshop para retocar retratos, crear doble exposición, efectos de película y mucho más. Un clic, resultado profesional.",
    category: "photo",
    tags: ["photo", "design", "presets"],
    stars: 4.7,
    saves: 16400,
    downloads: 61000,
    author: { name: "PixelForge", avatar: "PF", verified: false },
    thumbnail: "photo",
    type: "premium",
  },
  {
    id: "13",
    title: "Cinematic Title Animations",
    description: "40 animaciones de títulos estilo cine para After Effects. Incluye openers épicos, lower thirds y créditos finales.",
    category: "motion",
    tags: ["motion", "video", "templates"],
    badge: "official",
    stars: 4.9,
    saves: 18700,
    downloads: 74000,
    author: { name: "MotionLab", avatar: "ML", verified: true },
    thumbnail: "motion",
    type: "premium",
  },
  {
    id: "14",
    title: "Ambient & Chill Music Pack",
    description: "25 tracks ambient y chill sin copyright para streams, podcasts y vídeos de estudio. Perfectos para contenido lo-fi y mindfulness.",
    category: "audio",
    tags: ["audio", "music", "free"],
    stars: 4.7,
    saves: 21000,
    downloads: 87000,
    author: { name: "ChillWave", avatar: "CW", verified: true },
    thumbnail: "audio",
    type: "free",
  },
  {
    id: "15",
    title: "YouTube SEO & Growth Guide",
    description: "Guía completa de SEO para YouTube con estrategias probadas, plantillas de descripción, investigación de palabras clave y más.",
    category: "tutorials",
    tags: ["tutorials", "youtube", "design"],
    badge: "new",
    stars: 4.8,
    saves: 28500,
    downloads: 112000,
    author: { name: "GrowthHQ", avatar: "GH", verified: true },
    thumbnail: "tutorials",
    type: "free",
  },
  {
    id: "16",
    title: "Brand Color Palette Collection",
    description: "500 paletas de colores para branding y diseño de contenido. Incluye combinaciones para redes sociales, webs y packaging.",
    category: "color",
    tags: ["design", "templates", "social"],
    stars: 4.5,
    saves: 11200,
    downloads: 43000,
    author: { name: "ColorStudio", avatar: "CS", verified: false },
    thumbnail: "color",
    type: "free",
  },
  {
    id: "17",
    title: "Stock Video Pack — 4K Nature",
    description: "100 clips de vídeo stock 4K de paisajes, naturaleza y ciudad. Licencia libre de royalties para uso comercial y personal.",
    category: "stock",
    tags: ["video", "stock", "free"],
    badge: "trending",
    stars: 4.6,
    saves: 17800,
    downloads: 69000,
    author: { name: "StockVault", avatar: "SV", verified: true },
    thumbnail: "stock",
    type: "free",
  },
  {
    id: "18",
    title: "Midjourney Prompt Library",
    description: "1000+ prompts optimizados para Midjourney y DALL·E organizados por estilo: cinemático, anime, realista, abstracto y más.",
    category: "ai",
    tags: ["ai", "design", "templates"],
    badge: "new",
    stars: 4.8,
    saves: 36200,
    downloads: 128000,
    author: { name: "PromptCraft", avatar: "PC", verified: true },
    thumbnail: "ai",
    type: "free",
  },
  {
    id: "19",
    title: "Premiere Pro Plugin Suite",
    description: "Pack de 8 plugins para Premiere Pro: corrección de color automática, estabilizador mejorado, exportador rápido y más.",
    category: "plugins",
    tags: ["video", "plugins", "automation"],
    badge: "official",
    stars: 4.7,
    saves: 13400,
    downloads: 52000,
    author: { name: "ProTools", avatar: "PT", verified: true },
    thumbnail: "plugins",
    type: "premium",
  },
  {
    id: "20",
    title: "Podcast Cover Art Templates",
    description: "80 portadas para podcast con diseño profesional. Disponibles para Spotify, Apple Podcasts y más. Editables en Canva.",
    category: "templates",
    tags: ["templates", "audio", "design"],
    stars: 4.6,
    saves: 8300,
    downloads: 29000,
    author: { name: "PodDesign", avatar: "PD", verified: false },
    thumbnail: "templates",
    type: "free",
  },
  {
    id: "21",
    title: "Cinematic Color Grades – DaVinci",
    description: "30 grados de color cinemáticos para DaVinci Resolve inspirados en películas de Hollywood. Incluye nodos listos para importar.",
    category: "color",
    tags: ["video", "luts", "cinematic"],
    badge: "new",
    stars: 4.8,
    saves: 7100,
    downloads: 26500,
    author: { name: "GradeStudio", avatar: "GS", verified: true },
    thumbnail: "color",
    type: "free",
  },
  {
    id: "22",
    title: "Social Media Caption Pack",
    description: "500 captions listos para Instagram, TikTok y LinkedIn. Organizados por categoría: motivación, humor, lifestyle, marketing.",
    category: "templates",
    tags: ["templates", "social", "design"],
    badge: "trending",
    stars: 4.5,
    saves: 18900,
    downloads: 73000,
    author: { name: "CopyBox", avatar: "CB", verified: false },
    thumbnail: "templates",
    type: "free",
  },
  {
    id: "23",
    title: "Vocal Processing Preset Pack",
    description: "20 cadenas de procesado vocal para podcasts y voiceovers: compresión, EQ, reverb y saturation. Compatible con Reaper, Logic y Ableton.",
    category: "audio",
    tags: ["audio", "music", "sfx"],
    stars: 4.7,
    saves: 11300,
    downloads: 44000,
    author: { name: "VocalCraft", avatar: "VK", verified: true },
    thumbnail: "audio",
    type: "premium",
  },
  {
    id: "24",
    title: "3D Icon & Element Pack",
    description: "200 iconos y elementos 3D en formato PNG con fondo transparente. Perfectos para thumbnails, presentaciones y diseño web.",
    category: "motion",
    tags: ["motion", "design", "templates"],
    badge: "new",
    stars: 4.9,
    saves: 24500,
    downloads: 95000,
    author: { name: "3DFactory", avatar: "3F", verified: true },
    thumbnail: "motion",
    type: "free",
  },
  {
    id: "25",
    title: "After Effects Master Course",
    description: "Curso completo de After Effects desde cero: compositing, motion graphics, VFX y animación. 8 horas de vídeo + proyectos.",
    category: "tutorials",
    tags: ["tutorials", "motion", "video"],
    badge: "official",
    stars: 4.9,
    saves: 35600,
    downloads: 118000,
    author: { name: "MotionLab", avatar: "ML", verified: true },
    thumbnail: "tutorials",
    type: "premium",
  },
];

export const collections = [
  {
    id: "1",
    title: "Starter Pack para YouTubers",
    description: "Todo lo que necesitas para empezar: templates, música, LUTs y herramientas esenciales.",
    resources: 24,
    saves: 8900,
    author: "CretivHub",
    cover: "youtube",
    official: true,
  },
  {
    id: "2",
    title: "Pack completo After Effects",
    description: "Los mejores presets, plugins y proyectos de After Effects organizados por categoría.",
    resources: 48,
    saves: 12400,
    author: "MotionLab",
    cover: "aftereffects",
    official: false,
  },
  {
    id: "3",
    title: "Creador de Podcasts Pro",
    description: "Recursos de audio, templates para portadas, plantillas de descripción y más.",
    resources: 32,
    saves: 5600,
    author: "PodcastKit",
    cover: "podcast",
    official: true,
  },
  {
    id: "4",
    title: "Estética Retro / VHS",
    description: "Filtros, overlays, fuentes y música para crear contenido con estética retro años 80-90.",
    resources: 36,
    saves: 7800,
    author: "RetroVibes",
    cover: "retro",
    official: false,
  },
  {
    id: "5",
    title: "TikTok Creator Kit",
    description: "Templates verticales, música trending, efectos de sonido y fuentes para dominar los Shorts.",
    resources: 55,
    saves: 21300,
    author: "CretivHub",
    cover: "tiktok",
    official: true,
  },
  {
    id: "6",
    title: "Branding Kit Completo",
    description: "Paletas de color, tipografías, mockups y plantillas para construir una identidad visual sólida.",
    resources: 41,
    saves: 14700,
    author: "BrandStudio",
    cover: "branding",
    official: false,
  },
];

export const trending = [
  { pos: 1, change: "up",   title: "Sound FX Mega Pack",          category: "Audio",     stars: 4.9, downloads: 156000 },
  { pos: 2, change: "up",   title: "After Effects Master Course",  category: "Tutoriales",stars: 4.9, downloads: 118000 },
  { pos: 3, change: "up",   title: "Midjourney Prompt Library",   category: "IA",        stars: 4.8, downloads: 128000 },
  { pos: 4, change: "same", title: "YouTube SEO & Growth Guide",  category: "Tutoriales",stars: 4.8, downloads: 112000 },
  { pos: 5, change: "down", title: "YouTube Thumbnail Templates", category: "Templates", stars: 4.7, downloads: 98000 },
];
